runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

inbound_services:
- warmup

libraries:
- name: webob
  version: 1.2.3

- name: webapp2
  version: 2.5.2

handlers:
- url: /media
  static_dir: static/media/

- url: /static/admin
  static_dir: static/admin
  expiration: '0'

- url: /_ah/(mapreduce|queue|warmup|start|stop).*
  script: wsgi.application
  login: admin
  secure: always

- url: /.*
  script: wsgi.application
  login: admin
  secure: always

skip_files:
# default values first
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
# no unit tests need to be included
- ^(.*/)?tests.py$
- ^(.*/)?tests/*$
# don't upload google SDK
- ^libs/google_appengine/*
